# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  collector:
    image: collector
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5183:5183
    environment:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
      NATS_URL: nats://nats:4222
    networks:
      - com
    depends_on:
      - nats

  nats:
    image: nats:latest
    ports:
      - 4222:4222
    networks:
      - com

networks:
  com: {}
